sudo: false
cache: bundler
language: ruby
env:
  global:
    - secure: XLGH70Gu8eCbeyYDQr4VIxvduW/lsIxZBdYcSZLwY3ZHWwOnxvKCCIV12jgH+H1wTCUyGGuipGPv1XpkIP94kY6viAMVvakjmpYGw1A3Tt7PkF/WRrSnBelalb/OeGhj/C6wCgHtThfI20NtmtiOPd21FGjn0oogtZhxxuiKGg7PtviHFZUjHa5xYAvK12/QKERbUUDxEQmJIgvz+lHhtvYiVt0WQPJv5CNKhNAPWcZgbSZKXkLlNGjn5cX+4jrHjOmt+GJNH4eXyHzQ0EbNzavcSexKvfTEybWVifYmkyA6dZHUy/bo/FpDTi07fo2peMMUh7lJJdM3AMvZoovNssRLXy8EqOGYuEZ9AgpeXkSuiQjmez91pJj33P/QjWcdLX9eLNWSkdWhvXymyqoyMwp1uxofIbeY9QIiktsfp/R6iVHvk51JWtXlUOzrF2iVbXmSm9I8plMIrB7oEdVTb13K/ocx18GZ4HEnbSBndPrCroFx8HLBolDKgGQCHfestnSxf3Mw3BurWo9nxAJ1ypGTZ3UjMZslLQ/RjPTNT1Xa0rdnIQJB3n6OP2UnoFA4HdnoCKB05AeOMo/p1svOVfHIX+9J7UrhbzhH07/niE00+AG8CFfsUBOCH090+FDwZhLVqB41groX/o16RyFxN+DkFB5bI1G9pNVrTGKyfrU="
before_install:
  - 'if [[ $BUNDLE_GEMFILE == *master.gemfile ]]; then gem update --system; fi'
  - gem --version
  - gem install bundler
  - bundle --version
  - 'bundle config --local path ${BUNDLE_PATH:-$(dirname $BUNDLE_GEMFILE)/vendor/bundle}'
  - bundle config --local bin $PWD/bin
install: bundle update --jobs=3 --retry=3
script:
  - ./bin/rake travis
matrix:
  include:
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/chef-13.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.1.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.2.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.3.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.4.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.5.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.6.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.7.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.8.gemfile
    - rvm: 2.1.8
      gemfile: test/gemfiles/chef-12.9.gemfile
    - rvm: 2.1.8
      gemfile: test/gemfiles/chef-12.10.gemfile
    - rvm: 2.1.8
      gemfile: test/gemfiles/chef-12.11.gemfile
    - rvm: 2.1.8
      gemfile: test/gemfiles/chef-12.12.gemfile
    - rvm: 2.1.9
      gemfile: test/gemfiles/chef-12.13.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.14.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.15.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.16.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.17.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.18.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.19.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/chef-13.0.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/master.gemfile
